# BUILD Settings:
# ##############################################################################
[build]
  command = "npm run build"
  publish = ".next"

# PLUGINS
# ##############################################################################

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = '/plugins/netlify-plugin-contextual-auth'
  [plugins.inputs]
    username = 'Stanford'
    password = 'OnPurpose'
    context = ['branch-deploy', 'deploy-preview']
    file = '.next/_headers'

# HEADERS
# ##############################################################################
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "default-src https: 'unsafe-inline' 'unsafe-eval'; form-action https:; img-src https: data:; frame-ancestors https://app.storyblok.com"
    X-Content-Type-Options = "nosniff"
    X-Robots-Tag = "noindex, nofollow"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000"
    Permissions-Policy = "vibrate=(), geolocation=(), midi=(), notifications=(), push=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), speaker=()"

[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = true

# CONTEXTUAL PLUGINS
# ##############################################################################
# [[context.production.plugins]]
#   package = "netlify-plugin-submit-sitemap"
