export const root = 'relative w-full max-w-[29rem] sm:max-w-300 lg:max-w-[35rem] mx-auto break-words focus-visible:outline-none';
export const cardInner = 'relative w-full h-full aspect-w-1 aspect-h-2 duration-1000';
export const cardFront = 'group/front absolute w-full h-full top-0 left-0';
export const content = 'rs-px-0 absolute w-full h-2/5 bottom-0 left-0';
export const button = 'group/button absolute w-full h-full top-0 left-0 transition-all delay-200 group-aria-hidden/content:invisible';
export const flipIcon = 'absolute bottom-40 right-36 text-white w-65 h-65 border-2 border-white rounded-full p-16 group-hover/button:border-dashed group-focus/button:border-dashed group-aria-hidden/front:rotate-45';
export const cardContent = 'group/content aria-hidden:opacity-0 opacity-100 transition-opacity duration-700 absolute w-full h-full top-0 left-0 px-20 py-30 3xl:py-48 3xl:px-36 bg-gradient-to-b from-gc-black/70 to-gc-black/90 gc-changemaker children:children:children:!mb-1em';
export const imageWrapper = 'overflow-hidden aspect-w-1 aspect-h-2';
export const heading = 'mb-02em transition-opacity delay-100';
